
import type { Asset } from './types';

export const mockAssets: Asset[] = [
  {
    id: '1',
    purchaseDate: '2023-01-15',
    name: 'Laptop Pro 15"',
    invoiceNumber: 'INV-001',
    serialNumber: 'SN-LP001',
    assetTag: 'AT-001',
    supplier: 'sup-001', 
    category: 'Eletrônicos',
    purchaseValue: 1200.00,
    currentValue: 950.00,
    imageDateUris: [],
  },
  {
    id: '2',
    purchaseDate: '2023-02-20',
    name: 'Mesa de Escritório Grande',
    invoiceNumber: 'INV-002',
    serialNumber: 'N/A',
    assetTag: 'AT-002',
    supplier: 'sup-002', 
    category: 'Móveis',
    purchaseValue: 350.00,
    currentValue: 300.00,
    imageDateUris: [],
  },
  {
    id: '3',
    purchaseDate: '2022-11-05',
    name: 'Monitor Alta Resolução 27"',
    invoiceNumber: 'INV-003',
    serialNumber: 'SN-M001',
    assetTag: 'AT-003',
    supplier: 'sup-003', 
    category: 'Eletrônicos',
    purchaseValue: 450.00,
    currentValue: 380.00,
    imageDateUris: [],
  },
  {
    id: '4',
    purchaseDate: '2023-03-10',
    name: 'Cadeira Ergonômica',
    invoiceNumber: 'INV-004',
    serialNumber: 'N/A',
    assetTag: 'AT-004',
    supplier: 'sup-002', 
    category: 'Móveis',
    purchaseValue: 220.00,
    currentValue: 190.00,
    imageDateUris: [],
  },
  {
    id: '5',
    purchaseDate: '2023-01-25',
    name: 'Switch de Rede 24 Portas',
    invoiceNumber: 'INV-005',
    serialNumber: 'SN-NS001',
    assetTag: 'AT-005',
    supplier: 'sup-001', 
    category: 'Redes',
    purchaseValue: 280.00,
    currentValue: 250.00,
    imageDateUris: [],
  },
  {
    id: '6',
    purchaseDate: '2022-09-01',
    name: 'Projetor HD',
    invoiceNumber: 'INV-006',
    serialNumber: 'SN-PJ001',
    assetTag: 'AT-006',
    supplier: 'sup-003', 
    category: 'Eletrônicos',
    purchaseValue: 600.00,
    currentValue: 450.00,
    imageDateUris: [],
  },
  {
    id: '7',
    purchaseDate: '2023-04-02',
    name: 'Armário de Aço',
    invoiceNumber: 'INV-007',
    serialNumber: 'N/A',
    assetTag: 'AT-007',
    supplier: 'sup-002', 
    category: 'Móveis',
    purchaseValue: 150.00,
    currentValue: 130.00,
    imageDateUris: [],
  }
];
